<?php

namespace App\Controllers;

use TCPDF;
use App\Models\UserExportModel;
use CodeIgniter\Controller;

class PdfController extends Controller
{
    public function downloadUserData()
    {
        // Load the model to access the database
        $userModel = new UserExportModel();
        $users = $userModel->findAll();  // Fetch all users

        // Create a new TCPDF instance
        $pdf = new TCPDF();
        $pdf->SetCreator(PDF_CREATOR);
        $pdf->SetAuthor('YourApplication');
        $pdf->SetTitle('User Data');
        $pdf->SetHeaderData('', 0, 'User Data Report', 'Generated by CodeIgniter');

        // Set margins and other settings
        $pdf->SetMargins(15, 27, 15);
        $pdf->SetHeaderMargin(5);
        $pdf->SetFooterMargin(10);
        $pdf->SetAutoPageBreak(TRUE, 10);
        $pdf->AddPage();

        // Define HTML content with proper string encapsulation
        $html = '<h2>Lista de Usuarios</h2>';
        $html .= '<table border="1" cellpadding="5">';
        $html .= '<thead><tr>
            <th>ID</th>
            <th>Nombre de Usuario</th>
            <th>Email</th>
            <th>Rol</th>
            <th>Fecha de Creación</th>
        </tr></thead><tbody>';

        foreach ($users as $user) {
            $html .= '<tr>
                <td>' . $user['id'] . '</td>
                <td>' . $user['username'] . '</td>
                <td>' . $user['email'] . '</td>
                <td>' . $user['role'] . '</td>
                <td>' . $user['created_at'] . '</td>
            </tr>';
        }

        $html .= '</tbody></table>';

        // Write HTML to the PDF
        $pdf->writeHTML($html, true, false, true, false, '');

        // Force download of the PDF file
        $this->response->setContentType('application/pdf');
        $pdf->Output('UserData.pdf', 'D'); // 'D' forces a direct download
    }
}
